### ISSUE TITLE
gb-gae freezes when no flags are specified

### ISSUE THREAD

**Issue by abiosoft** [PalmStoneGames/gb-gae#1]
I noticed that gb-gae freezes when no flags are specified.
##### Expected behaviour

Show usage.
##### How to reproduce

Run gb-gae without specifying flags.

``` shell
$ gb-gae
```

Run gb-gae with argument(s) but no flags

``` shell
$ gb-gae help
```
##### Environment

``` shell
$ go version
go version go1.4.2 darwin/amd64
```

**Comment by luna-duclos** [comment]
gb-gae isn't intended to be run directly, try running this instead:

```
gb gae 
```

I should however, make this clear in the readme, unlike now

**Comment by abiosoft** [comment]
Oops, my bad!!!.

I should know better.
